exclude: "^databricks_src|^data_engineering/"
repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ['--skip-string-normalization'] #prevents conversion of single to double quotes see https://safjan.com/black-keep-single-quotes-strings/
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.10.0]
        args: ['--max-line-length=88', '--extend-ignore=E203,E704']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        exclude: "^helm/"
        args: [--unsafe]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
